
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb-standalone
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: always

volumes:
  mongo-data:
